### PR TITLE
Separate status response handling from formatting

### LINKED ISSUE #34: Empty Response with Status does not send a status
To reproduce: 
From any Domain class::__invoke `return $this->payload->withStatus(PayloadInterface::STATUS_NOT_FOUND);`

return this and the header data will say 200 OK; if I add a `->withOutput('anything');` I will get the proper status header. 404

I have tracked this down to src/Responder/FormattedResponder.php::53 `if ($this->hasOutput($payload) {` 

It seems like that is there for a reason, and I was going to make some edits and submit a pull request but I'm struggling to get the test environment set up for tonight. So I'll submit an issue instead.

### PR DESCRIPTION
**Pull request by shadowhand**
Response body formatting should not be tied to status, as it prevents
having responses with no body. For example, a 204 No Content response
without a body is perfectly acceptable.

Fixes #34

### CODE REVIEW

File: tests/Fake/FakeDomain.php [hunk 1]
```diff
@@ -11,7 +11,7 @@ class FakeDomain implements DomainInterface
     public function __invoke(array $input)
     {
         return (new Payload())
-            ->withStatus(Payload::OK)
```
Comment (shadowhand) [inline tests/Fake/FakeDomain.php]: A separate PR needs to be made against `equip/adr` to drop the deprecated status codes.

File: composer.json [hunk 2]
```diff
@@ -9,9 +9,10 @@
             "homepage": "https://github.com/equip"
         }
     ],
+    "minimum-stability": "alpha",
     "require": {
         "php": ">=5.5",
-        "equip/adr": "^1.3",
+        "equip/adr": "^2.0",
```
Comment (shadowhand) [inline composer.json]: Released `2.0.0-alpha1` to ensure that deprecated constants are not used in 2.0.

File: composer.json [hunk 3]
```diff
@@ -9,9 +9,10 @@
             "homepage": "https://github.com/equip"
         }
     ],
+    "minimum-stability": "alpha",
```
Comment (shadowhand) [inline composer.json]: This will need to be removed before release.

**Comment by shadowhand** [comment]
@equip/contributors please review. This may be sufficient to do a feature freeze and release the first alpha of 2.0. I don't know of any other changes we need to make.

File: src/Formatter/AbstractFormatter.php [hunk 4]
```diff
@@ -48,33 +34,4 @@ public static function accepts()
...
     abstract protected function body(PayloadInterface $payload);
-
-    /**
-     * Get the response status from the payload.
-     *
-     * @param PayloadInterface $payload
-     *
-     * @return integer
-     */
-    public function status(PayloadInterface $payload)
```
Comment (shadowhand) [inline src/Formatter/AbstractFormatter.php]: I thought about making this into an interface now that there are no implemented methods, but that's not possible with protected methods.

Comment (AlexMasterov) [inline src/Formatter/AbstractFormatter.php]: @shadowhand I see no reason not to make the interface here. The interface can be useful to simplify Responder. 

To simplify [the Responder](https://scrutinizer-ci.com/g/equip/framework/code-structure/master/class/Equip%5CResponder%5CFormattedResponder) probably should make a separate class for "Content Negotiation" `NegotiationResponder`. Then `FormatterResponder` only be used to format a formatter (not Payload object, it has already been processed), where exactly will need such an interface for type hinting.

Also please don't rush with release and a feature freeze.

Comment (AlexMasterov) [inline src/Formatter/AbstractFormatter.php]: @shadowhand I have conceptual question here. Can services Responder to modify the Payload object using `Payload::withMessages`? (by convention)

I think that Payload messages is only needed for them and so they can use them for interesting combinations. Then Formatters can modify the output.

Comment (shadowhand) [inline src/Formatter/AbstractFormatter.php]: Interfaces can't define `protected` methods, so we can't use an interface.

Comment (shadowhand) [inline src/Formatter/AbstractFormatter.php]: @AlexMasterov payload cannot be modified in responders because the payload is immutable. Modifications would affect the current responder only.

Comment (AlexMasterov) [inline src/Formatter/AbstractFormatter.php]: @shadowhand Even knowing about this feature I keep thinking how-to modify or to traverse it.. But with the interface I read your message. I just don't understand why not make this method public?

I like the way it's done now. I was referring to [the Scrutinizer CI metrics](https://scrutinizer-ci.com/g/equip/framework/code-structure/master/class/Equip%5CResponder%5CFormattedResponder).

Comment (shadowhand) [inline src/Formatter/AbstractFormatter.php]: Because the method doesn't need to be used publicly?

Comment (shadowhand) [inline src/Formatter/AbstractFormatter.php]: Actually I'm [totally wrong][1], these methods are always used publicly. 😨 I will update the PR.

[1]: https://github.com/equip/framework/blob/542d1c3f38f8871c18a00bd8d9161b0cb2009bf2/src/Responder/FormattedResponder.php#L131-L135

Comment (AlexMasterov) [inline src/Formatter/AbstractFormatter.php]: @shadowhand But in a concrete formatters it's public. I'm confused.

Comment (AlexMasterov) [inline src/Formatter/AbstractFormatter.php]: @shadowhand Now I understand. After this discussion I was thinking to quit programming :relaxed:

Comment (shadowhand) [inline src/Formatter/AbstractFormatter.php]: @AlexMasterov abstract has been converted into an interface.

File: tests/Fake/FakeDomain.php (hunk 1 above)
Comment (shadowhand) [inline tests/Fake/FakeDomain.php]: This has been done.

**Comment by shadowhand** [comment]
@equip/contributors this is now ready for final review.

File: tests/Responder/StatusResponderTest.php [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+
+    public function testEmptyPayload()
+    {
+        $payload = new Payload;
+        $request = $this->getMockBuilder('Psr\Http\Message\ServerRequestInterface')->getMock();
+        $response = $this->getMockBuilder('Psr\Http\Message\ResponseInterface')->getMock();
+        $returned = call_user_func($this->responder, $request, $response, $payload);
+        $this->assertSame($returned, $response);
+    }
+}
```
Comment (elazar) [inline tests/Responder/StatusResponderTest.php]: Add `use` directives and use `::class` for all PSR-7 interface references?

Comment (shadowhand) [inline tests/Responder/StatusResponderTest.php]: Done.

File: src/Responder/FormattedResponder.php [hunk 6]
```diff
@@ -149,11 +148,11 @@ protected function assertValid(array $data)
...
 
         foreach ($data as $formatter => $quality) {
-            if (!is_subclass_of($formatter, AbstractFormatter::class)) {
+            if (!is_subclass_of($formatter, FormatterInterface::class)) {
                 throw new InvalidArgumentException(sprintf(
                     'All formatters in `%s` must implement `%s`',
                     static::class,
-                    AbstractFormatter::class
+                    FormatterInterface::class
                 ));
```
Comment (AlexMasterov) [inline src/Responder/FormattedResponder.php]: Maybe for better readability and reducing line of code to make a separate class for exceptions?

File: tests/Responder/FormattedResponderTest.php [hunk 7]
```diff
@@ -86,7 +81,7 @@ public function testSorting()
 
     /**
      * @expectedException InvalidArgumentException
-     * @expectedExceptionMessageRegExp /formatters .* must implement .*AbstractFormatter/i
+     * @expectedExceptionMessageRegExp /formatters .* must implement .*FormatterInterface/i
```
Comment (sctape) [inline tests/Responder/FormattedResponderTest.php]: Do we have a standard for setting expected exceptions in annotations versus method calls?

**Comment by sctape** [comment]
Looks like this PR needs a rebase if it's being merged into dev.

File: tests/Fake/FakeDomain.php (hunk 1 above)
Comment (elazar) [inline tests/Fake/FakeDomain.php]: May be a good idea to note the PR that made this change for posterity, as it doesn't appear to be mentioned anywhere in this one presently.

**Comment by elazar** [comment]
👍

File: tests/Fake/FakeDomain.php (hunk 1 above)
Comment (shadowhand) [inline tests/Fake/FakeDomain.php]: equip/adr#5

File: tests/Responder/FormattedResponderTest.php (hunk 7 above)
Comment (shadowhand) [inline tests/Responder/FormattedResponderTest.php]: Fixed.

**Comment by shadowhand** [comment]
@sctape @elazar rebased.

**Comment by sctape** [comment]
👍
